[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader',
    'chmod -R 755 storage bootstrap/cache',
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/framework/cache/data',
    'mkdir -p storage/logs',
    'mkdir -p bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
